# -*- coding: utf-8 -*-
from .base import BaseTool
from .base import PrintUtils, CmdTask, FileUtils, EnvUtils, check_admin
from .base import osversion, osarch
import os
import sys
import json
import re
import zipfile
import shutil
import subprocess
import urllib.request
import urllib.error

class Tool(BaseTool):
    def __init__(self):
        self.name = "一键安装 ARM GCC 工具链"
        self.type = BaseTool.TYPE_INSTALL
        self.author = '小鱼'
        
        # 从配置文件获取安装目录
        try:
            # 尝试从父目录导入配置
            parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            if parent_dir not in sys.path:
                sys.path.insert(0, parent_dir)
            import config
            if hasattr(config, 'ARM_GCC_INSTALL_DIR'):
                self.install_dir = config.ARM_GCC_INSTALL_DIR
            else:
                # 如果配置文件中没有，使用默认值
                self.install_dir = r'D:\CodeTools\Compiler'
        except:
            # 如果导入失败，使用默认值
            self.install_dir = r'D:\CodeTools\Compiler'
        
        # GitHub API 端点
        self.github_api_url = 'https://api.github.com/repos/carlosperate/arm-none-eabi-gcc-action/releases/latest'
        
        # 后备版本（如果无法从 GitHub 获取）
        self.fallback_version = '15.2.Rel1'
        self.msys2_profile_name = 'arm-none-eabi-gcc.sh'

    def is_valid_msys2_path(self, path):
        """检查路径是否是有效的 MSYS2 安装目录"""
        if not path or not os.path.exists(path):
            return False

        bash_path = os.path.join(path, 'usr', 'bin', 'bash.exe')
        if os.path.exists(bash_path):
            return True

        pacman_dir = os.path.join(path, 'etc', 'pacman.d')
        if os.path.exists(pacman_dir):
            return True

        path_name = os.path.basename(path.rstrip(os.sep))
        if path_name in ['msys64', 'msys32']:
            usr_dir = os.path.join(path, 'usr')
            if os.path.exists(usr_dir):
                return True

        return False

    def get_msys2_path(self):
        """获取 MSYS2 安装路径"""
        paths = None
        try:
            import config
            if hasattr(config, 'MSYS2_PATHS'):
                paths = config.MSYS2_PATHS
        except ImportError:
            try:
                parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
                if parent_dir not in sys.path:
                    sys.path.insert(0, parent_dir)
                import config
                if hasattr(config, 'MSYS2_PATHS'):
                    paths = config.MSYS2_PATHS
            except Exception:
                pass

        if paths is None:
            paths = [
                r'C:\msys64',
                r'C:\msys32',
                os.path.expanduser(r'~\msys64'),
                os.path.expanduser(r'~\msys32')
            ]

        for path in paths:
            path_name = os.path.basename(path.rstrip(os.sep))
            is_likely_parent_dir = path_name not in ['msys64', 'msys32']

            if is_likely_parent_dir and os.path.exists(path):
                for subdir in ['msys64', 'msys32']:
                    sub_path = os.path.join(path, subdir)
                    if self.is_valid_msys2_path(sub_path):
                        return sub_path
                continue

            if self.is_valid_msys2_path(path):
                return path

        return None

    def to_msys2_unix_path(self, windows_path):
        """将 Windows 路径转换为 MSYS2 可识别的 Unix 风格路径"""
        normalized = os.path.abspath(windows_path).replace('\\', '/')
        if len(normalized) >= 2 and normalized[1] == ':':
            drive = normalized[0].lower()
            rest = normalized[2:]
            return f"/{drive}{rest}"
        return normalized

    def get_msys2_profile_file(self, msys2_path):
        profile_dir = os.path.join(msys2_path, 'etc', 'profile.d')
        return os.path.join(profile_dir, self.msys2_profile_name)

    def configure_msys2_armgcc_path(self, bin_path):
        """将 ARM GCC bin 路径添加到 MSYS2 启动环境"""
        msys2_path = self.get_msys2_path()
        if not msys2_path:
            PrintUtils.print_warning("未检测到 MSYS2，跳过 MSYS2 环境配置")
            return False

        PrintUtils.print_info(f"检测到 MSYS2 安装目录: {msys2_path}")
        choice = input("是否将 ARM GCC 添加到 MSYS2 启动环境？[Y/n]: ").strip().lower()
        if choice in ['n', 'no']:
            PrintUtils.print_info("跳过 MSYS2 环境配置")
            return False

        profile_file = self.get_msys2_profile_file(msys2_path)
        profile_dir = os.path.dirname(profile_file)
        try:
            os.makedirs(profile_dir, exist_ok=True)
            msys2_bin_path = self.to_msys2_unix_path(bin_path)
            content = (
                "# Auto-generated by ARM GCC installer\n"
                f'export PATH="{msys2_bin_path}:$PATH"\n'
            )
            with open(profile_file, 'w', encoding='utf-8') as f:
                f.write(content)
            PrintUtils.print_success(f"已写入 MSYS2 配置: {profile_file}")
            PrintUtils.print_info("请重新打开 MSYS2 终端或执行 source /etc/profile 生效")
            return True
        except Exception as e:
            PrintUtils.print_error(f"写入 MSYS2 配置失败: {e}")
            return False

    def cleanup_msys2_armgcc_path(self):
        """清理 ARM GCC 写入的 MSYS2 profile 配置"""
        msys2_path = self.get_msys2_path()
        if not msys2_path:
            return True

        profile_file = self.get_msys2_profile_file(msys2_path)
        if not os.path.exists(profile_file):
            return True

        try:
            os.remove(profile_file)
            PrintUtils.print_success(f"已清理 MSYS2 配置: {profile_file}")
            return True
        except Exception as e:
            PrintUtils.print_warning(f"清理 MSYS2 配置失败，请手动删除: {profile_file}")
            PrintUtils.print_warning(str(e))
            return False

    def get_latest_version_from_github(self):
        """使用 GitHub API 获取最新 release，并从 release notes 中解析工具链版本号
        
        Returns:
            str: 工具链版本号，如果获取失败返回 None
        """
        try:
            PrintUtils.print_info("正在从 GitHub 获取最新版本信息...")
            
            # 创建请求
            req = urllib.request.Request(self.github_api_url)
            req.add_header('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)')
            
            # 发送请求
            with urllib.request.urlopen(req, timeout=10) as response:
                data = json.loads(response.read().decode('utf-8'))
                
                # 获取 release notes
                body = data.get('body', '')
                tag_name = data.get('tag_name', '')
                
                PrintUtils.print_info(f"GitHub Release: {tag_name}")
                
                # 尝试从 release notes 中解析版本号
                # 格式可能是: "Add `15.2.Rel1`" 或 "15.2.Rel1" 等
                # 匹配类似 15.2.Rel1, 14.3.Rel1, 12.3.Rel1 等格式
                version_patterns = [
                    r'`?(\d+\.\d+\.Rel\d+)`?',  # 匹配 `15.2.Rel1` 或 15.2.Rel1
                    r'(\d+\.\d+\.Rel\d+)',      # 匹配 15.2.Rel1
                    r'(\d+\.\d+-\d{4}-q\d)',    # 匹配旧格式如 10-2020-q4
                ]
                
                for pattern in version_patterns:
                    match = re.search(pattern, body, re.IGNORECASE)
                    if match:
                        version = match.group(1)
                        PrintUtils.print_success(f"解析到工具链版本: {version}")
                        return version
                
                # 如果无法从 body 中解析，尝试从 tag_name 或其他字段获取
                PrintUtils.print_warning("无法从 release notes 中解析版本号")
                return None
                
        except urllib.error.URLError as e:
            PrintUtils.print_warning(f"无法连接到 GitHub API: {e}")
            return None
        except json.JSONDecodeError as e:
            PrintUtils.print_warning(f"解析 GitHub API 响应失败: {e}")
            return None
        except Exception as e:
            PrintUtils.print_warning(f"获取版本信息时发生错误: {e}")
            return None

    def get_download_url(self, version):
        """构建 Arm 官方的下载 URL
        
        Args:
            version: 工具链版本号（如 '15.2.Rel1'）
            
        Returns:
            str: 下载 URL
        """
        # Windows x86_64 版本的下载 URL 格式
        # https://developer.arm.com/-/media/Files/downloads/gnu/{version}/binrel/arm-gnu-toolchain-{version}-mingw-w64-i686-arm-none-eabi.zip
        base_url = 'https://developer.arm.com/-/media/Files/downloads/gnu'
        filename = f'arm-gnu-toolchain-{version}-mingw-w64-i686-arm-none-eabi.zip'
        url = f'{base_url}/{version}/binrel/{filename}'
        return url

    def download_toolchain(self, version, target_dir):
        """下载工具链 zip 文件
        
        Args:
            version: 工具链版本号
            target_dir: 目标目录
            
        Returns:
            str: 下载的文件路径，如果失败返回 None
        """
        try:
            # 确保目标目录存在
            os.makedirs(target_dir, exist_ok=True)
            
            # 构建下载 URL
            download_url = self.get_download_url(version)
            PrintUtils.print_info(f"下载 URL: {download_url}")
            
            # 临时文件路径
            temp_dir = os.environ.get('TEMP', '.')
            zip_filename = f'arm-gnu-toolchain-{version}-mingw-w64-i686-arm-none-eabi.zip'
            zip_path = os.path.join(temp_dir, zip_filename)
            
            # 下载文件
            if not FileUtils.download(download_url, zip_path):
                return None
            
            return zip_path
            
        except Exception as e:
            PrintUtils.print_error(f"下载工具链时发生错误: {e}")
            return None

    def extract_toolchain(self, zip_path, target_dir):
        """使用 zipfile 模块解压工具链到目标目录
        
        Args:
            zip_path: zip 文件路径
            target_dir: 目标目录（D:\CodeTools\Compiler）
            
        Returns:
            str: 解压后的工具链目录路径，如果失败返回 None
        """
        try:
            # 创建 arm-none-eabi-gcc 子目录
            armgcc_dir = os.path.join(target_dir, 'arm-none-eabi-gcc')
            PrintUtils.print_info(f"正在解压到: {armgcc_dir}")
            
            # 确保目标目录存在
            os.makedirs(armgcc_dir, exist_ok=True)
            
            # 打开 zip 文件
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                # 获取所有文件列表
                file_list = zip_ref.namelist()
                
                # 查找根目录（通常是第一个目录）
                root_dir = None
                for name in file_list:
                    if '/' in name:
                        root_dir = name.split('/')[0]
                        break
                    elif '\\' in name:
                        root_dir = name.split('\\')[0]
                        break
                
                if not root_dir:
                    PrintUtils.print_error("无法确定压缩包的根目录")
                    return None
                
                # 解压所有文件到 arm-none-eabi-gcc 目录
                zip_ref.extractall(armgcc_dir)
                
                # 返回解压后的完整路径
                extracted_path = os.path.join(armgcc_dir, root_dir)
                PrintUtils.print_success(f"解压完成: {extracted_path}")
                
                return extracted_path
                
        except zipfile.BadZipFile:
            PrintUtils.print_error("无效的 zip 文件")
            return None
        except Exception as e:
            PrintUtils.print_error(f"解压工具链时发生错误: {e}")
            return None

    def get_bin_path(self, toolchain_dir):
        """获取 bin 目录的完整路径
        
        Args:
            toolchain_dir: 工具链根目录
            
        Returns:
            str: bin 目录路径，如果不存在返回 None
        """
        bin_path = os.path.join(toolchain_dir, 'bin')
        if os.path.exists(bin_path):
            return bin_path
        return None

    def find_armgcc_bin_path(self, armgcc_root_dir):
        """在 arm-none-eabi-gcc 根目录下稳健查找可用的 bin 目录。"""
        if not armgcc_root_dir or not os.path.exists(armgcc_root_dir):
            return None

        # 优先 1: 直接安装为 arm-none-eabi-gcc\bin
        direct_bin = os.path.join(armgcc_root_dir, 'bin')
        if os.path.exists(os.path.join(direct_bin, 'arm-none-eabi-gcc.exe')):
            return direct_bin

        # 优先 2: 常见结构 arm-none-eabi-gcc\arm-gnu-toolchain-xxx\bin
        for item in os.listdir(armgcc_root_dir):
            item_path = os.path.join(armgcc_root_dir, item)
            if not os.path.isdir(item_path):
                continue
            candidate_bin = os.path.join(item_path, 'bin')
            if os.path.exists(os.path.join(candidate_bin, 'arm-none-eabi-gcc.exe')):
                return candidate_bin

        # 兜底: 递归查找 arm-none-eabi-gcc.exe 并回推 bin 目录
        for root, _, files in os.walk(armgcc_root_dir):
            if 'arm-none-eabi-gcc.exe' in files:
                return root
        return None

    def check_installed(self):
        """检查是否已安装（目录扫描 + PATH 全局检测）"""
        armgcc_dir = os.path.join(self.install_dir, 'arm-none-eabi-gcc')
        if os.path.exists(armgcc_dir):
            bin_path = self.find_armgcc_bin_path(armgcc_dir)
            if bin_path:
                return True, bin_path, "local"

        # fallback: 从 PATH 全局检测（外部安装也可识别）
        try:
            result = subprocess.run(
                ['where', 'arm-none-eabi-gcc'],
                capture_output=True,
                text=True,
                encoding='utf-8',
                errors='replace',
                timeout=10
            )
            if result.returncode == 0:
                lines = [x.strip().strip('"') for x in result.stdout.splitlines() if x.strip()]
                for exe_path in lines:
                    if not exe_path.lower().endswith('.exe'):
                        continue
                    if not os.path.exists(exe_path):
                        continue
                    bin_path = os.path.dirname(exe_path)
                    gcc_exe = os.path.join(bin_path, 'arm-none-eabi-gcc.exe')
                    if os.path.exists(gcc_exe):
                        return True, bin_path, "external"
        except Exception:
            pass

        return False, None, None

    def uninstall(self, bin_path, install_source="local"):
        """卸载 ARM GCC：根据来源清理 PATH/目录。"""
        PrintUtils.print_info("开始卸载 ARM GCC 工具链...")

        # 1) 清理 PATH（系统优先，同时兼容用户 PATH）
        if bin_path:
            bin_path_abs = os.path.abspath(bin_path)
            PrintUtils.print_info("正在从 PATH 环境变量移除:")
            PrintUtils.print_info(f"  {bin_path_abs}")
            EnvUtils.remove_from_path_environment([bin_path_abs], prefer_system=True)

        # 1.5) 清理 MSYS2 profile 配置
        self.cleanup_msys2_armgcc_path()

        # 2) 删除安装目录（仅本工具安装来源）
        if install_source != "local":
            PrintUtils.print_warning("检测为外部安装来源：仅清理 PATH，不删除未知安装目录")
            PrintUtils.print_success("ARM GCC 卸载清理完成!")
            return True

        armgcc_dir = os.path.join(self.install_dir, 'arm-none-eabi-gcc')
        if os.path.exists(armgcc_dir):
            try:
                shutil.rmtree(armgcc_dir, ignore_errors=False)
                PrintUtils.print_success(f"已删除安装目录: {armgcc_dir}")
            except Exception as e:
                PrintUtils.print_error(f"删除安装目录失败: {e}")
                PrintUtils.print_warning("你可以稍后手动删除该目录（可能被占用）")
                return False
        else:
            PrintUtils.print_info("未找到安装目录，无需删除文件")

        PrintUtils.print_success("ARM GCC 卸载完成!")
        return True

    def run(self):
        """运行安装流程"""
        PrintUtils.print_info("=" * 60)
        PrintUtils.print_info("ARM GCC 工具链一键安装工具")
        PrintUtils.print_info("安装 Arm GNU Embedded Toolchain (arm-none-eabi-gcc)")
        PrintUtils.print_info("=" * 60)
        PrintUtils.print_info("")

        # 检查是否已安装
        is_installed, bin_path, install_source = self.check_installed()
        if is_installed:
            source_text = "本工具安装目录" if install_source == "local" else "系统 PATH(外部安装)"
            PrintUtils.print_success(f"检测到 ARM GCC 工具链已安装在: {bin_path}")
            PrintUtils.print_info(f"检测来源: {source_text}")
            PrintUtils.print_info("")
            PrintUtils.print_info("请选择操作:")
            PrintUtils.print_info("  1. 重新安装")
            if install_source == "local":
                PrintUtils.print_info("  2. 卸载（清理 PATH + 删除安装目录）")
            else:
                PrintUtils.print_info("  2. 卸载（仅清理 PATH，不删除外部安装目录）")
            PrintUtils.print_info("  3. 退出")
            op = input("请选择 [1/2/3]: ").strip()
            if op == '2':
                # 二次确认
                if install_source == "local":
                    PrintUtils.print_warning("警告: 将清理 PATH 并删除本工具安装目录中的工具链文件")
                else:
                    PrintUtils.print_warning("警告: 将仅清理 PATH，不会删除外部安装目录中的工具链文件")
                confirm = input("确定要卸载吗？[y/N]: ").strip().lower()
                if confirm in ['y', 'yes']:
                    self.uninstall(bin_path, install_source=install_source)
                else:
                    PrintUtils.print_info("取消卸载")
                return
            elif op == '3' or op == '0':
                PrintUtils.print_info("退出")
                return
            else:
                # 1 或其他输入，继续走重新安装流程
                pass

        # 获取最新版本
        version = self.get_latest_version_from_github()
        if not version:
            PrintUtils.print_warning(f"无法从 GitHub 获取版本，使用后备版本: {self.fallback_version}")
            version = self.fallback_version
        else:
            PrintUtils.print_success(f"将安装版本: {version}")

        PrintUtils.print_info("")

        # 下载工具链
        PrintUtils.print_info("开始下载工具链...")
        zip_path = self.download_toolchain(version, self.install_dir)
        if not zip_path:
            PrintUtils.print_error("下载失败")
            return

        PrintUtils.print_info("")

        # 解压工具链
        PrintUtils.print_info("开始解压工具链...")
        toolchain_dir = self.extract_toolchain(zip_path, self.install_dir)
        if not toolchain_dir:
            PrintUtils.print_error("解压失败")
            # 清理下载的文件
            try:
                if os.path.exists(zip_path):
                    os.remove(zip_path)
            except:
                pass
            return

        # 获取 bin 目录路径（兼容多种压缩包目录结构）
        armgcc_root = os.path.join(self.install_dir, 'arm-none-eabi-gcc')
        bin_path = self.find_armgcc_bin_path(armgcc_root)
        
        # 验证 bin 目录是否存在
        if not bin_path or not os.path.exists(bin_path):
            PrintUtils.print_error(f"未找到 bin 目录: {bin_path}")
            return

        PrintUtils.print_info("")

        # 添加到环境变量（只添加这一个路径）
        bin_path_abs = os.path.abspath(bin_path)
        PrintUtils.print_info(f"正在添加以下路径到系统 PATH 环境变量:")
        PrintUtils.print_info(f"  {bin_path_abs}")
        if EnvUtils.add_to_system_path([bin_path_abs], skip_if_not_admin=True):
            PrintUtils.print_success("已添加到 PATH 环境变量")
        else:
            PrintUtils.print_warning("添加到 PATH 环境变量失败，请手动添加")
            PrintUtils.print_info(f"请手动将以下路径添加到 PATH: {bin_path}")

        PrintUtils.print_info("")
        self.configure_msys2_armgcc_path(bin_path_abs)

        PrintUtils.print_info("")

        # 清理临时文件
        try:
            if os.path.exists(zip_path):
                os.remove(zip_path)
                PrintUtils.print_info("已清理临时文件")
        except:
            pass

        # 安装完成
        PrintUtils.print_success("=" * 60)
        PrintUtils.print_success("安装完成!")
        PrintUtils.print_info("")
        PrintUtils.print_info("使用说明:")
        PrintUtils.print_info("  1. Windows 终端：请重新打开命令行窗口以使 PATH 生效")
        PrintUtils.print_info("  2. MSYS2 终端：请重新打开终端，或执行 source /etc/profile")
        PrintUtils.print_info("  3. 运行以下命令验证安装:")
        PrintUtils.print_info("     arm-none-eabi-gcc --version")
        PrintUtils.print_info("")
        PrintUtils.print_info(f"安装路径: {toolchain_dir}")
        PrintUtils.print_info(f"Bin 目录: {bin_path}")
        PrintUtils.print_success("=" * 60)

